version: '3'
services:
  selenium:
    shm_size: 2gb
    build:
      context: .
      dockerfile: Dockerfile.chrome
      args:
        progress: plain
    container_name: chrome_instance
    ports:
      - "4444:4444"

  selenium_python:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        progress: plain
    container_name: crawler
    depends_on:
      - selenium
      
  selenium_python_location_update:
    build:
      context: .
      dockerfile: Dockerfile.python_location_update
      args:
        progress: plain
    container_name: crawler_location_update
    depends_on:
      - selenium